sudo: required
services:
  - docker

before_install:
  - docker build -t amankumar16/complex-nginx -f ./client/Dockerfile.dev ./client

scripts:
  - docker run amankumar16/complex-nginx npm run test -- --coverage

after_success:
  - docker build -t amankumar16/complex-client ./client
  - docker build -t amankumar16/complex-server ./server
  - docker build -t amankumar16/complex-nginxx ./nginx
  - docker build -t amankumar16/complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amankumar16/complex-client
  - docker push amankumar16/complex-server
  - docker push amankumar16/complex-nginxx
  - docker push amankumar16/complex-worker